import {map} from "rxjs";

export class Countries{

  countries:{readonly id:number,readonly country:string }[]=[
    {id: 0, country: "Andorra"},
    {id: 1, country: "Australia"},
    {id: 2, country: "Belgium"},
    {id: 3, country: "Denmark"},
    {id: 4, country: "Germany"},
    {id: 5, country: "Estonia"},
    {id: 6, country: "Finland"},
    {id: 7, country: "France"},
    {id: 8, country: "Greece"},
    {id: 9, country: "Ireland"},
    {id: 10, country: "Iceland"},
    {id: 11, country: "Israel"},
    {id: 12, country: "Italy"},
    {id: 13, country: "Japan"},
    {id: 14, country: "Canada"},
    {id: 15, country: "Korea"},
    {id: 16, country: "Latvia"},
    {id: 17, country: "Liechtenstein"},
    {id: 18, country: "Lithuania"},
    {id: 19, country: "Luxembourg"},
    {id: 20, country: "Malaysia"},
    {id: 21, country: "Malta"},
    {id: 22, country: "Monaco"},
    {id: 23, country: "New Zealand"},
    {id: 24, country: "Netherlands"},
    {id: 25, country: "Norway"},
    {id: 26, country: "Austria"},
    {id: 27, country: "Poland"},
    {id: 28, country: "Portugal"},
    {id: 29, country: "San Marino"},
    {id: 30, country: "Sweden"},
    {id: 31, country: "Switzerland"},
    {id: 32, country: "Singapore"},
    {id: 33, country: "Slovenia"},
    {id: 34, country: "Spain"},
    {id: 35, country: "Czech Republic"},
    {id: 36, country: "Hungary"},
    {id: 37, country: "United States"},
    {id: 38, country: "United Kingdom"},
    {id: 39, country: "Cyprus"},
    {id: 40, country: "Other"},
  ];
}
